version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
